version: '3'

services:
  db:
    image: postgres:9.6.5
    expose:
      - 5432
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    working_dir: /var/recipes
    volumes:
      - .:/var/recipes
    ports:
      - "8000:8000"
      - "2222:22"
    depends_on:
      - db

volumes:
  postgres_data:
  .:
