# Generated by Django 2.1.7 on 2019-03-07 00:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('url', models.CharField(blank=True, max_length=1024, verbose_name='url')),
                ('ingredients', models.TextField(verbose_name='ingredients')),
                ('directions', models.TextField(verbose_name='directions')),
                ('ingredients_json', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='ingredients json')),
                ('directions_json', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='directions json')),
                ('image_url', models.CharField(blank=True, max_length=1024, verbose_name='image url')),
                ('status', models.SmallIntegerField(choices=[(0, 'created'), (8, 'hidden'), (9, 'public')], default=0, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'verbose_name': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='SourceWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='url')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name_plural': 'source websites',
                'verbose_name': 'source website',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipes', to='recipes.SourceWebsite', verbose_name='source website'),
        ),
    ]
