
RECIPE_STATUS_CREATED = 0
RECIPE_STATUS_HIDDEN = 8
RECIPE_STATUS_PUBLIC = 9

RECIPE_STATUS_CHOICES = (
	(RECIPE_STATUS_CREATED, "created"),
	(RECIPE_STATUS_HIDDEN, "hidden"),
	(RECIPE_STATUS_PUBLIC, "public"),
)
