# Generated by Django 2.1.7 on 2019-04-09 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0003_auto_20190313_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.SourceWebsite', verbose_name='source')),
            ],
            options={
                'verbose_name': 'scraper',
                'verbose_name_plural': 'scrapers',
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField(default=True, verbose_name='is success')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='finished')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scrapers.Scraper', verbose_name='scraper')),
            ],
            options={
                'verbose_name': 'scraper log',
                'verbose_name_plural': 'scraper logs',
            },
        ),
    ]
